version: '3.7'

volumes:
    logs:
        driver: local

services:
    web:
        build:
            context: .
        image: backend_phptest
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    mysql_host:
        image: mysql:8
        restart: always
        container_name: cn_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: phptest
            MYSQL_PASSWORD: phptest
            MYSQL_ROOT_PASSWORD: phptest
            MYSQL_DATABASE: local_phptest
        # sync folders. MySQL data is stored outside container so that rebuilding doesn't clear db.
        # folder is at workspace root.
        volumes:
            - ./mysql:/var/lib/mysql:rw
            - ./data/sql/create_database.sql:/docker-entrypoint-initdb.d/1.sql:ro
            - ./data/sql/load_fixtures.sql:/docker-entrypoint-initdb.d/2.sql:ro
            - ./data/sql/update_database.sql:/docker-entrypoint-initdb.d/3.sql:ro
